### ISSUE TITLE
Project 'net.sourceforge.plantuml.lib' is missing required library: '\Users\travkin\Documents\git-repos\plantuml4eclipse\bundles\net.sourceforge.plantuml.lib\lib\plantuml-epl-1.2023.11.jar'

### ISSUE THREAD

**Issue by OepenerPlatt** [OepenerPlatt/plantuml#1]
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/2a91b264-83d2-42ca-b054-0e6675ec5192)

**Comment by OepenerPlatt** [comment]
Removed build path entry  (already defined in manifest.MF/runtime
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/65b563d4-4d95-4e9b-8fec-de547bc6a455)

**Comment by travkin79** [comment]
Hi @OepenerPlatt,
If you merge the latest changes from master branch to your fork, this issue should disappear. Now, I'm using relative paths for libraries (and these are automatically downloaded from the PlantUML project's releases on GitHub).
