### ISSUE TITLE
The import net.sourceforge.plantuml.FileFormat cannot be resolved

### ISSUE THREAD

**Issue by OepenerPlatt** [OepenerPlatt/plantuml#3]
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/8c0ecadf-2d95-4d1c-8cb9-407efd8b5cb1)

**Comment by OepenerPlatt** [comment]
seems to calm down the eclipse ide not being aware of the exported packages.
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/603afab5-4afc-4254-87c5-576b08f512ee)

**Comment by travkin79** [comment]
The latest commit from master branch has the plantuml.jar in the classpath. You should merge from master to your development branch in your fork.

![image](https://github.com/OepenerPlatt/plantuml/assets/10887297/c9caa43e-de15-424d-b19c-86f39ae251dd)

**Comment by pbrossel** [comment]
Yes, I'll rebase asap.
The jar was already available in the lib folder in the project.
Eclipse did not realize that it was there. 
So I removed it (1) and added it again (2+3) and the errors were gone.
