### ISSUE TITLE
IDE does not start - Caused by: java.lang.NoClassDefFoundError: org.eclipse.swt.SWTError

### ISSUE THREAD

**Issue by OepenerPlatt** [OepenerPlatt/plantuml#5]
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/e99dcb13-da53-4118-a0e0-47950064663c)

**Comment by OepenerPlatt** [comment]
![image](https://github.com/OepenerPlatt/plantuml/assets/67123535/ecd1be11-2749-42b9-b847-c9f601db977c)

**Comment by travkin79** [comment]
I think, that's because the launch config is aimed for MacOS. I think, it would be a good idea, to create an additional launch config for Windows, with the win32-specific SWT and maybe other platform-specific required libs.
